### ISSUE TITLE
CFR Estimate

### ISSUE THREAD

**Issue by mhoehle** [dirkschumacher/covid-19-indicators#1]
https://www.lshtm.ac.uk/newsevents/news/2020/diamond-princess-cruise-ship-new-estimates-highlight-successes-and-failures

However, for the CFR I think it's important that there is a strong age dependence. So the raw values depend very much on the population. Possibly report by age-groups?

**Comment by dirkschumacher** [comment]
Thanks for the report. I was thinking the same re. age groups. I am not sure though how to best summarise them in a table without blowing up the page.

**Comment by dirkschumacher** [comment]
Added an age group column and CFR is now generated from a CSV. Planning to put everything in CSVs eventually
